# 밑바닥부터 시작하는 딥러닝

## 목차

* 헬로 파이썬
* 퍼셉트론
* 신경망
* 신경망 학습
* 오차역전파법
* 학습 관련 기술들
* 합성곱 신경망(CNN)
* 딥러닝

In [1]:
import numpy as np

In [2]:
A = np.array(
    [
        [1,2],
        [3,4]
    ]
)

B = np.array(
    [10, 20]
)

A*B

array([[10, 40],
       [30, 80]])

In [3]:
A.flatten()

array([1, 2, 3, 4])

In [4]:
A > 2

array([[False, False],
       [ True,  True]])

In [5]:
A.flatten() > 2

array([False, False,  True,  True])

In [11]:
def AND(x1, x2):
    w1, w2, theta = 0.5, 0.5, 0.7
    tmp = x1*w1 + x2*w2
    if tmp <= theta:
        return 0
    elif tmp > theta:
        return 1

In [15]:
AND(0, 0), AND(1, 0), AND(0, 1), AND(1, 1)

(0, 0, 0, 1)

In [7]:
x = np.array(
    [0,1]
)

w = np.array(
    [0.5, 0.5]
)

b = -0.7

In [8]:
w*x

array([0. , 0.5])

In [9]:
np.sum(w*x)

0.5

In [10]:
np.sum(w*x) + b

-0.19999999999999996

In [8]:
def AND(x1, x2):
    x = np.array([x1, x2])
    w = np.array([0.5, 0.5])
    b = -7
    tmp = np.sum(w*x) + b
    if tmp <= 0:
        return 0
    else:
        return 1
    

In [9]:
def AND(x1, x2):
    w1, w2, theta = 0.5, 0.5, 0.7
    tmp = x1*w1 + x2*w2
    if tmp <= theta:
        return 0
    elif tmp > theta:
        return 1

def NAND(x1, x2):
    x = np.array([x1, x2])
    w = np.array([-0.5,-0.5])
    b = 0.7
    tmp = np.sum(w*x) + b
    if tmp <= 0:
        return 0
    else:
        return 1
    
def OR(x1, x2):
    x = np.array([x1, x2])
    w = np.array([0.5, 0.5])
    b = -0.2
    tmp = np.sum(w*x) + b
    if tmp <= 0:
        return 0
    else:
        return 1

In [10]:
def XOR(x1, x2):
    s1 = NAND(x1, x2)
    s2 = OR(x1, x2)
    y = AND(s1, s2)
    return y

In [11]:
XOR(0,0),XOR(1,0),XOR(0,1),XOR(1,1)

(0, 1, 1, 0)

## 신경망

In [ ]:
def step_function(x):
    if x > 0:
        return 1
    else:
        return 0